# Generated by Django 5.2.5 on 2025-09-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('CASA', 'casa'), ('APT', 'apartamento'), ('SAL', 'Sala Comercial')], max_length=10)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='cadastro.locador')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='cadastro.locador')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='cadastro.locatario')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='cadastro.imovel')),
            ],
        ),
    ]
