# Generated by Django 5.2.5 on 2025-09-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_imovel_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='cadastro.contrato')),
            ],
        ),
    ]
